### ISSUE TITLE
General macOS issues

### ISSUE THREAD

**Issue by johnnovak** [jcmoyer/Nuked-SC55#10]
Managed to compile this successfully on macOS by following the build instructions, but the binaries don't seem to do much... As you can see, the executables just exit without a warning. The main executable doesn't display the GUI, and the renderer doesn't even do anything when the `--help` param is specified. Huh?

Any tips?

<img width="539" alt="image" src="https://github.com/user-attachments/assets/a830c1a8-5879-4b1b-ae8b-e68a1be512bb">

The installation step went well and all the files appear to be in the correct place:

<img width="398" alt="image" src="https://github.com/user-attachments/assets/8d4303ef-e307-44be-87ff-447fe2a86935">

**Comment by jcmoyer** [comment]
If I had to guess, since it's at least printing "No input file specified" it's probably failing in this function: https://github.com/jcmoyer/Nuked-SC55/blob/master/src/path_util.cpp#L11

**Comment by jcmoyer** [comment]
Can you test the commit I just pushed? I don't have a mac to test, but I think it should be correct. If not, someone else will have to give it a go.

**Comment by johnnovak** [comment]
Thanks for the quick fix @jcmoyer, that resolved the startup issue 🎉 

It turns out I had the ROM files in the wrong place, and with this change I'm getting an error message indicating that:

<img width="863" alt="image" src="https://github.com/user-attachments/assets/3c620498-66f8-46e3-a816-39c3adebee46">

Once I put them into `share/nuked-sc55`, everything is hunky dory 🥳 (ignore the JACK server not running part)

<img width="1728" alt="image" src="https://github.com/user-attachments/assets/2aa4953e-2777-41df-aa52-fc2df7cac8ba">
