### ISSUE TITLE
LCD's window caption always shows Nuked SC-55: SC-55mkII regardless of used ROM set

### ISSUE THREAD

**Issue by Falcosoft** [jcmoyer/Nuked-SC55#3]
In FE_CreateInstance() fe->emu.Init() calls LCD_Init() before emu.LoadRoms() is called. But this way LCD_Init() always gets default value for mcu.romset.
In theory this can also cause problems for Window size in case of JV880 ROM set but I could not test it (I have no such ROM set).

**Comment by jcmoyer** [comment]
Thanks for the report, this should be fixed in ca10a5583730a9b73602b966960905e04582d76f
