### ISSUE TITLE
.wav renderings with SC-55 v1.21 ROM set are 20% too slow

### ISSUE THREAD

**Issue by kajott** [jcmoyer/Nuked-SC55#4]
I have two ROM sets: One from an SC-55 mk1 v1.21, and another one from an SC-55 mk2.

The SC-55 mk2 ROM set works fine, no worries.

With the SC-55 mk1 v1.21 ROM set, though, files rendered with `nuked-sc55-render` play ca. 20% too slowly; other than that, they are fine (correct pitch, no audible glitches, etc.) Running `nuked-sc55` realtime with the same ROM set with Falcosoft MIDI Player + loopMIDI is also no problem, only rendering is.

Reset type (`-r gs`/`-r gm`) and output format (`-f s16`/`-f f32`) don't make a difference.

**Platform:** multiple (tested with Windows 11 23H2 and Ubuntu 22.04)
**Compiler/Settings:** multiple (tested with Visual Studio 2022 and GCC 11, Release builds)
**Version:** `2ad1315` (latest as of writing), but the problem existed in the old `renderer` branch already

**Comment by jcmoyer** [comment]
Should be fixed in fe25d21ccb495707d8982bac0ed8e704f17b9020
