### ISSUE TITLE
The new S32 output format's volume seems to be not normalized (half of S16's output volume)

### ISSUE THREAD

**Issue by Falcosoft** [jcmoyer/Nuked-SC55#5]
The new S32 output format's volume seems to be not normalized.
It's exactly half of S16 format's output volume (and 1/4 of F32 format's).
Currently when converting to S16 format the sample values are right shifted by 15 bits (not 16!). It seems with 15 bit right shift the individual sample values never reach the min/max values of S16 range (-32768/32767). 
In case of S32 format you would get the same amplitude level if you actually left shifted the sample values by 1 bit.   

This way you would get the same output level as S16, but better resolution than S16. (It seems the emulator currently produces sample data that can be represented fully in 17-bits).  

Edit:
BTW, In case of F32 format currently the equivalent of 14-bit right shift is used. This can produce sample values beyond the normalized range (-1.0f/+1.0f) in case of very high volume Midi files but it is not a problem since floating point samples cannot clip in the strict sense (the -1.0f/+1.0f range is a soft limit, not a hard limit).

**Comment by jcmoyer** [comment]
I don't really have an opinion on what the audio levels should be, but it is definitely too quiet so I just left shifted by 1 as suggested.
