### ISSUE TITLE
CPU Utilization on Linux.

### ISSUE THREAD

**Issue by hubby4** [jcmoyer/Nuked-SC55#6]
OS: Debian 12 (Bookworm)
DE: KDE 5.27 w/ Wayland

GCC 13.2.0 - Built from scratch
RTMIDI 6.0.0 - Built from scratch

Debian Packages - Latest updates

libsdl2-dev
cmake

I built the latest version of this Nuked-SC55 fork, and Cmake reports no errors. However, performance is worse than Nuked-SC55 official version. Nuked-SC55 official version usually uses 80% to 90% CPU utilization of a single core on my system. This fork is utilizing 100% even when idle and not in use. This results in garbled sound when in use with dosbox. It's strange because a Windows XP build of this fork built by Falcosoft utilizes the same CPU % as the Nuked-SC55 official version. I'm guessing that the fault is mine, but since Cmake is not giving me any errors, it's difficult to now where to start diagnosing the problem.

**Comment by jcmoyer** [comment]
Hi, can you post the commands you ran to build the project?

**Comment by hubby4** [comment]
From the source folder:

mkdir build
cd build
cmake ..
cmake --build . --config Release
make
sudo make install

**Comment by jcmoyer** [comment]
Actually I think I misunderstood how cmake works with makefiles on linux. Forget the previous comment; try this instead (from source folder):

```
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release ..
cmake --build .
cmake --install .
```

**Comment by hubby4** [comment]
I tried the -DCMAKE_BUILD_TYPE instructions above and it built without errors, but the program still utilizing too much CPU.

Curiously, when I tried building with CLANG, it spit out this error message.

/home/debian/Downloads/jcmoyer/src/cast.h:9:40: error: no type named 'source_location' in namespace 'std'
inline R RangeCast(T value, const std::source_location where = std::source_location::current())
                                  ~~~~~^
/home/debian/Downloads/jcmoyer/src/cast.h:9:69: error: no member named 'source_location' in namespace 'std'
inline R RangeCast(T value, const std::source_location where = std::source_location::current())
                                                               ~~~~~^

**Comment by jcmoyer** [comment]
Did you delete the entire build directory and start over from scratch? Also how garbled is the audio? Can you make out any of the sound or is it totally unlistenable?

As for clang, your version isn't recent enough - I think you'll need 15.0.0 or 16.0.0. You could try removing the source_location stuff  in that file and replacing the body with just `return (R)value;` but I don't know if your clang will fail on something else.

**Comment by hubby4** [comment]
I created a new build directory.

It sounds like a bad AM radio connection. I can hear some sound, but a lot of static too.

I'll try out your suggestions later tonight. Thanks.

**Comment by jcmoyer** [comment]
Some benchmarks on `Linux arch 6.9.5-arch1-1 #1 SMP PREEMPT_DYNAMIC x86_64 GNU/Linux`, i5-2500k in various configurations:

compiler     | options                           | work thread CPU (`top -H`)
-|-|-
gcc 14.1.1   |                                   | 61-63%
clang 17.0.6 |                                   | 58-60%
gcc 14.1.1   | LTO, -march=native, -mtune=native | 56-58%
clang 17.0.6 | LTO, -march=native, -mtune=native | 56-57%

Enabling these flags is probably the easiest way to get some free performance, but the results are more or less identical to what I'm seeing on Windows so I don't think there's a Linux specific problem. I will have to do some proper benchmarking and see if there are any easy performance wins.

**Comment by hubby4** [comment]
I tried all your suggestions, but the results are still consistent. Thank you for trying.

I'll stick with the Nuked official build and Falcosoft's test build with Eivind's optimizations.

Oh BTW, clang 15, 16, and 17 report this error for me.

[ 76%] Linking CXX executable nuked-sc55
/usr/bin/ld: CMakeFiles/nuked-sc55.dir/src/main_frontend.cpp.o: undefined reference to symbol '_ZSt20__throw_length_errorPKc@@GLIBCXX_3.4'
/usr/bin/ld: /usr/local/lib64/libstdc++.so.6: error adding symbols: DSO missing from command line
clang-17: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [CMakeFiles/nuked-sc55.dir/build.make:117: nuked-sc55] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:113: CMakeFiles/nuked-sc55.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2

**Comment by jcmoyer** [comment]
Sorry that it didn't work out, I'll see if I can optimize the backend a bit. As for clang, I forgot that you need to use `-DCMAKE_CXX_COMPILER=clang++` not `=clang`. I edited my original comment.

**Comment by jcmoyer** [comment]
Hi @hubby4, I've pushed some commits to master that reduced the CPU usage from 56% to 45% on my hardware. If you decide to give them a try let me know your experience.

**Comment by hubby4** [comment]
This is a massive improvement for me. On the previous build, nuked-sc55 was utilizing 92% to 100% of a single CPU core while idle. Now idle single core usage is 33%. When in use, single core usage climbs to 50-60%. This is now my go-to nuked-sc55 build for this system.

**Comment by jcmoyer** [comment]
Excellent, then I'll consider this fixed.
