### ISSUE TITLE
Location of rtmidi?

### ISSUE THREAD

**Issue by linoshkmalayil** [jcmoyer/Nuked-SC55#9]
I am confused as to which directory to place the rtmidi repo.
I tried the directories: 
Nuked-SC55/3rdparty/rtmidi
Nuked-SC55/rtmidi
Nuked-SC55/src/rtmidi
Nuked-SC55/cmake/rtmidi

But all of them I get the following error:
```
-- Could NOT find rtmidi (missing: rtmidi_DIR)
-- Configuring done (0.1s)
CMake Error in CMakeLists.txt:
  Imported target "RtMidi::rtmidi" includes non-existent path

    "RTMIDI_INCLUDE_DIR-NOTFOUND"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



-- Generating done (0.0s)
CMake Generate step failed.  Build files cannot be regenerated correctly.
```
I am trying to compile for Arch Linux and RaspberryPi 
I hope I am not missing something simple.

**Comment by jcmoyer** [comment]
If rtmidi is installed system-wide, it should be located automatically. You can also pass `-DCMAKE_PREFIX_PATH=<path>` at the first cmake invocation if you built and installed it elsewhere.

**Comment by linoshkmalayil** [comment]
Thanks,
First I was under the assumption that the SC55 source code will compile rtmidi code to generate the libraries.
After that it took a while for me to figure out compiling them and installing them systemwide on Raspberry Pi.
